<?php header('Content-Type: text/html; charset=UTF-8'); ?>
<?php $this->headTitle('Find Publisher'); ?>
<?php //$this->layout()->instructions = ""; ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>   
   <div class="col-md-4">
    <form class="form-horizontal" method="post" action="<?=$this->url('find_publisher')?>">
        <div class="form-group">
            <label class="col-xs-3 control-label">Name: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="name_publisher" id="findpublisher-name" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-3 control-label">Location: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="location_publisher" id="findpublisher-location" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-10">
                <button type="submit" class="btn btn-default" name="search1">Search</button>
            </div>
        </div>
    </form>   
</div>
<?php //} ?>
</body>
</html>
