<?php $this->headTitle('Find Publisher'); ?>
<div class="col-md-4">
    <form class="form-horizontal" method="get" action="<?=$this->url('manage_publisher')?>">
        <div class="form-group">
            <label class="col-xs-3 control-label">Name: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="name" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-3 control-label">Location: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="location" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-10">
                <button type="submit" class="btn btn-default">Search</button>
            </div>
        </div>
    </form>   
</div>
