<?php $this->headTitle('New Agent Type'); ?>
<?php //$this->layout()->instructions = ""; ?>
<?php                                       
               /* if ($request->getqueryParams('action') !== null) 
                {   
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                } */
        
        
 ?>
<div class="col-md-4">
    <form class="form-horizontal" method="post" action="<?=$this->url('login')?><?='?action=new'?>">
        <div class="form-group">
            <label class="col-xs-3 control-label">User Name: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="user_name" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-3 control-label">Password: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="user_pwd" />
            </div>
        </div>
        <div class="form-group">
            <label for="role">Select role (select one):</label>
                <select class="form-control" id="role" name="role">
                <option>Administrator</option>
                <option>User</option>
                </select>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-10">
                <button type="submit" class="btn btn-default" name="submitt" value="Save">Login</button>
            </div>
        </div>
    </form>   
</div>