<?php $this->headTitle('Manage Publisher'); ?>
<div class="col-md-9">
<p>
<?php foreach (range('A', 'Z') as $char) { 
        //for ($char = 'A'; $char <= 'Z'; $char++) { ?>
    <a href="#"><?php echo ' '.$char.' '.'|'  ?></a>    
<?php } ?>
</p>
        <table class="table table-striped table-condensed" style="font-size:10pt;">
        <thead>
        <tr>
          <th>Name</th>
		  <th>Locations</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
		<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
        <?php foreach($this->rows as $row) : ?>
        <tr>
        <td><?php echo $escaper->escapeHtml($row['name']); ?></td>
        <td>            
        <?php   $output = (array)$row;
                $params = implode(', ', $output);        
        ?>        
        <a href="<?=$this->url('manage_PublisherLocation')?><?php echo '?row='. urlencode($params);  ?>">Manage Locations</a>              
        </td>
        <td>            
            <?php $output = (array)$row;
                  $params = implode(', ', $output);        
            ?>        
            <a href="<?=$this->url('edit_publisher')?><?php echo '?row='. urlencode($params);  ?>">Edit</a>        
            |
            <a href="<?=$this->url('delete_publisher')?><?php echo '?id='. $row['id'].'&term='. $row['name'];  ?>">Delete</a>
        </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
		</table>
        <?php if($this->countp > 1) { ?>
        <form method="get" action="page">
            <?=$this->paginationControl($this->rows,
                'Sliding',
                'app::controls',
                [
                    'route'  => 'manage_publisher',
                    'extraParams' => $searchParams,
                ]
            );?>
        </form>
        <?php } ?>
        </div>
</div>
