<?php $this->headTitle('Manage Publisher Locations'); ?>
<?php //$this->layout()->instructions = ""; ?>

<?php                                       
        $id;
        if ($request->getqueryParams() !== null) 
        {   
            $queryString = implode('',$request->getqueryParams());
            $params = explode(',',$queryString);              
        } 
        if ($params[0] !== null) 
        {   
            echo '<b>Publisher: </b>'.$params[1].'<br/>'; ?>
            <a href="<?=$this->url('edit_language')?><?php echo '?id=' . $params[0]. '&pub_name='. $params[1];  ?>">Add Location</a> 
       <?php } 
        
 ?>

