<?php $this->headTitle('Manage Work'); ?>
<?php $this->viewModel()->setRoot(new \Zend\View\Model\ViewModel()) ?>
<?php $this->layout()->instructions = "Create a new card (use the lookup function to retrieve basic information based on the title) or select a title to review, change or publish an existing card."; ?>
<div class="row">
    <div class="col-md-4">
        <h2>
                Coming Soon
        </h2>
       
    </div>
</div>
