<?php $this->headTitle('MyPage'); ?>

<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">My First Zend Page</span></h1>
    <p>
        Congratulations! You have successfully installed the
        <a href="http://www.masterzendframework.com/zend-expressive-introduction/" target="_blank"> How to install and configure 
		zend-expressive skeleton application</a>.
        This skeleton can serve as a simple starting point for you to begin building your application.
    </p>
    <p>
        Expressive builds on zend-stratigility to provide a minimalist PSR-7 middleware framework for PHP.
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>
                <i class="fa fa-plane"></i> Agent type
        </h2>
        <p>
            Gives my name.
        </p>
       <table class='gridtable'>
        <tr>
          <th>Id</th>
          <th>Type</th>
        </tr>
		<?php foreach($this->rows as $row) : ?>
		<tr>
		<td><?php echo $row['id']; ?></td>
		<td><?php echo $row['type']; ?></td>
        </tr>
		<?php endforeach; ?>
		</table>
    </div>
</div>
