<?php $this->headTitle('New Publisher'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-md-4">
    <form class="form-horizontal" method="post" action="<?=$this->url('new_publisher')?>">
        <div class="form-group">
            <label class="col-xs-2 control-label">Name: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="name_publisher" id="newpublisher" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default">Save</button>
            </div>
        </div>
    </form>   
</div>
