<?php $this->headTitle('Delete Publisher'); ?>
<?php //$this->layout()->instructions = "The english words cannot be changed."; ?>
<?php                                       
               $id;
                if ($request->getqueryParams('id') !== null) 
                {   
                    $params = $request->getqueryParams();
                    $id = $params['id'];
                }
?>
<?php if($_POST['submitt'] == 'Delete') { ?>
<div class="col-xs-4">
       <form method="post" action="<?=$this->url('manage_publisherlocation')?><?='?id=' . $params['id'] . '&count=0'?>">
        <p>Are you sure you want to delete this location for the publisher?</p>
        <ul>
        <li>
        <?php 
            $locs = [];
            foreach($_POST['selectchk1'] as $loc) {
                $locs[] = $loc;
                echo $loc . "<br />";
            }  
        ?>
        </li>
        <input type="hidden" name="id" value="<?=$id?>">
        <input type="hidden" name="action" value="<?='delete'?>">
        <?php                             
             foreach($_POST['selectchk1'] as $loc) { ?>
             <input type="hidden" name="locs[]" value="<?=$loc?>">
        <?php     } ?>
        <?php    
            //fetch location ids of locations selected for delete    
            $row = [];
            $table = new \App\Db\Table\PublisherLocation($adapter);
            $row = $table->findLocationId($id, $locs);
            //var_dump($row);
            foreach($row as $locid) { ?>
            <input type="hidden" name="locids[]" value="<?=$locid['id']?>">
        <?php     } ?>
        </ul>
        <input type="submit" name="submitt" value="Delete"> 
        <input type="submit" name="submitt" value="Cancel">
       </form>
   </div>
<?php } ?>
<?php if($_POST['submitt'] == 'Merge') { ?>
<div class="col-xs-4">
    <form method="post" action="<?=$this->url('manage_publisherlocation')?><?='?id=' . $params['id'] . '&count=0'?>">
    <p>Are you sure you want to merge these?</p>
        <ul>
        <li>
        <?php 
            $source_locs;
            $dest_loc;
            foreach($_POST['selectsource'] as $sourceloc) {
                $source_locs = unserialize($sourceloc); 
        ?>
                <input type="hidden" name="sourceids[]" value="<?=$source_locs['id']?>">
        <?php 
                echo $source_locs['location'] . "<br />";
            }
            $dest_loc = unserialize($_POST['selectdest']);
            //var_dump($dest_loc[0]['location']);
            echo "To " . $dest_loc[0]['location'];
        ?>
        </li>
        <input type="hidden" name="id" value="<?=$id?>">
        <input type="hidden" name="action" value="<?='merge'?>">        
        <input type="hidden" name="destid" value="<?=$dest_loc[0]['id']?>">
        </ul>
        <input type="submit" name="submitt" value="Merge"> 
        <input type="submit" name="submitt" value="Cancel">
    </form>
</div>   
<?php } ?>
