<?php $this->headTitle('Delete Publisher'); ?>
<?php //$this->layout()->instructions = "The english words cannot be changed."; ?>
<?php                                       
               $id;
                if ($request->getqueryParams('id') !== null) 
                {   
                    $params = $request->getqueryParams();
                    $id = $params['id'];
                }
?>
<?php if($_POST['submitt'] == 'Delete') { ?>
<div class="col-xs-4">
       <form method="post" action="<?=$this->url('manage_publisherlocation')?><?='?id=' . $params['id'] . '&count=0'?>">
        <p>Are you sure you want to delete this location for the publisher?</p>
        <ul>
        <li>
        <?php 
            $locs = [];
            foreach($_POST['selectchk1'] as $loc) {
                $locs[] = $loc;
                echo $loc . "<br />";
            }  
            //var_dump($locs);
            
            //$name = $row['name'];
        ?>
        </li>
        <input type="hidden" name="id" value="<?=$id?>">
        <input type="hidden" name="action" value="<?='delete'?>">
        <?php                             
             foreach($_POST['selectchk1'] as $loc) { ?>
             <input type="hidden" name="locs[]" value="<?=$loc?>">
        <?php     } ?>
        <?php    
            //fetch location ids of locations selected for delete    
            $row = [];
            $table = new \App\Db\Table\PublisherLocation($adapter);
            $row = $table->findLocationId($id, $locs);
            //var_dump($row);
            foreach($row as $locid) { ?>
            <input type="hidden" name="locids[]" value="<?=$locid['id']?>">
        <?php     } ?>
        </ul>
        <input type="submit" name="submitt" value="Delete"> 
        <input type="submit" name="submitt" value="Cancel">
       </form>
   </div>
<?php } ?>
<?php if($_POST['submitt'] == 'Merge') { ?>
    <p> coming soon </p>
<?php } ?>
