<?php $this->headTitle('Delete Publisher'); ?>
<?php //$this->layout()->instructions = "The english words cannot be changed."; ?>
<?php                                       
                $id;
                if ($request->getqueryParams('id') !== null) 
                {   
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                    $id = $params['id'];
                    //fetch name based on id
                    $table = new \App\Db\Table\PublisherLocation($adapter);
                    $row = $table->findPublisherId($id);
                    $location = $row['location'];
                    //echo $location;
                } ?>
   <div class="col-xs-4">
       <form method="post" action="<?=$this->url('manage_publisherlocation')?><?='?id=' . $params['id'] . '&count=1'?>">
        <p>Are you sure you want to delete this location for the publisher?</p>
        <ul>
        <li><?=$location?>
        </li>
        <input type="hidden" name="id" value="<?=$id?>">
        <input type="hidden" name="action" value="<?=$action?>">
        </ul>
        <input type="submit" name="submitt" value="Delete"> 
        <input type="submit" name="submitt" value="Cancel">
       </form>
   </div>