<?php $this->headTitle('Edit Publisher'); ?>
<?php //$this->layout()->instructions = ""; ?>

<?php                                       
         $id;
                if ($request->getqueryParams('id') !== null) 
                {   
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                    $id = $params['id'];
                } 
        
 ?>
<div class="col-md-4">
<form class="form-horizontal" method="post" action="<?=$this->url('manage_publisher')?>">
<input type="hidden" name="action" value="<?php echo $action; ?>">
<input type="hidden" name="id" value="<?php echo $id; ?>">
  <div class="form-group">   
	<label class="col-xs-2 control-label">Name: </label>
	<div class="col-xs-7">    
		<input type="text" class="form-control" name="publisher_newname" id="newpublishername" value="<?php echo $params['term']; ?>" />
	</div>
  </div>
  <div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button> 
        <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
	</div>
  </div>
</form>
</div>

