<?php $this->headTitle('Manage Publisher'); ?>
<div class="col-md-9">
<p>
<?php foreach ($this->carat as $value) { ?>
    <a href="<?=$this->url('manage_publisher')?><?='?letter='. $value['letter']. '&action=alphasearch'?>">
    <?php echo ' '.$value['letter'].' '; ?></a><?php echo '|';  ?>
<?php } ?>
</p>
        <table class="table table-striped table-condensed" style="font-size:10pt;">
        <thead>
        <tr>
          <th>Name</th>
		  <th>Locations</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
		<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
        <?php foreach($this->rows as $row) : ?>
        <tr>
        <td><?php echo $escaper->escapeHtml($row['name']); ?></td>
        <td>            
        <?php   $output = (array)$row;
                $params = implode(', ', $output);  
                $cnt = count($row);
               /* echo "params is \n";
                var_dump($params);
                echo "count of row is \n".$cnt; */
        ?>        
        <a href="<?=$this->url('manage_publisherlocation')?><?='?id='. $row['id'] . '&count=' . $cnt?>">Manage Locations</a>              
        </td>
        <td>                   
            <a href="<?=$this->url('edit_publisher')?><?='?id='. $row['id']. '&action=edit'?>">Edit</a>        
            |
            <a href="<?=$this->url('delete_publisher')?><?='?id='. $row['id']. '&action=delete'?>">Delete</a>
        </td>
        </tr>
        <?php endforeach; ?>
        </tbody>
		</table>
        <?php if($this->countp > 1) { ?>
        <form method="get" action="page">
            <?=$this->paginationControl($this->rows,
                'Sliding',
                'app::controls',
                [
                    'route'  => 'manage_publisher',
                    'extraParams' => $searchParams,
                ]
            );?>
        </form>
        <?php } ?>
        </div>
</div>
