<?php $this->headTitle('Manage Publisher Locations'); ?>
<?php //$this->layout()->instructions = ""; ?>

<div class="col-md-9">
<?php                                       
        $id;
        if ($request->getqueryParams() !== null) 
        {   
            /*$queryString = implode('',$request->getqueryParams());
            $params = explode(',',$queryString); */
            $params = $request->getqueryParams();
            //$action = $params['action'];
            $id = $params['id'];           
        } 
        if ($id !== null) 
        {   
             //fetch name based on id
            $table = new \App\Db\Table\Publisher($adapter);
            //echo $id;
            $row = $table->findRecordById($id);
            //var_dump($row);
            $name = $row['name'];
            echo '<b>Publisher: </b>'.$name.'<br/>'; 
?>
            <a href="<?=$this->url('add_publisher_location')?><?='?id=' . $id. '&action=new'?>">Add Location</a> 
<?php   } ?>
<form class="form-horizontal">
<table class="table table-striped table-condensed" style="font-size:10pt;">
     <thead>
         <tr>
             <th>Select</th>
             <th>Location</th>
             <th>Source</th>
             <th>Destination</th>
         </tr>
     </thead>
     <tbody>
     <?php $escaper = new Zend\Escaper\Escaper('utf-8');
        foreach($this->rows as $row) : ?>
     <form>
         <tr>
             <td>
                 <div class="checkbox">
                     <label><input type="checkbox" id='select' name="selectchk1[]"></label>
                 </div>
             </td>
             <td>
                 <?php echo $escaper->escapeHtml($row['location']); ?>
             </td>     
             <td>
                 <div class="checkbox">
                     <label><input type="checkbox" id='select' name="selectchk2"></label>
                 </div>
             </td> 
             <td>
                 <div class="radio">
                     <label><input type="radio" id='select' name="selectradio"></label>
                 </div>
             </td>
         </tr>
         <?php endforeach; ?>
         </tbody>
</table>
<?php
if(isset($_POST['delete'])){
if(!empty($_POST['selectchk1'])){
foreach($_POST['check_list'] as $selected){
echo $selected."</br>";
}
}
}
?>
<div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default" name="delete">
                <a href="<?=$this->url('delete_publisher_location')?><?='?id=' . $id. '&action=delete'?>" style="text-decoration:none;">Delete</a>
                </button>
                <button type="submit" class="btn btn-default" name="merge">
                <a href="<?=$this->url('delete_publisher_location')?><?='?id=' . $id. '&action=delete'?>" style="text-decoration:none;">Merge</a>
                </button>
            </div>
</div>
</form>
</div>