<?php $this->headTitle('Merge Publisher'); ?>
<?php //$this->layout()->instructions = ""; ?>

<script type="text/javascript">
function setText(target) {
var temp = $('input[name=select_source]:checked').val();
var tf = document.getElementById("sourcepublisher");
tf.value = temp;
}	
</script>

<div class="col-lg-10">
<form class="form-horizontal" method="post" action="<?=$this->url('manage_publisher')?>" style="font-size:8pt;" id="merge_form" name="merge_form">
  <input type="hidden" name="action" value="merge_publisher">
<table cellspacing="0" cellpadding="4" border="0" style="font-size:10pt;">
<tr class="col-lg-12">

<div class="col-lg-6">
<td>
Source Publisher<br /><br />
<div class="form-group">
    <label class="col-xs-2 control-label">Find: </label>
    <div class="col-xs-7">
        <input type="text" class="form-control" name="source_publisher" id="sourcepublisher" size="50" maxlength="100"/>
    </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default" name="submitt" value="Find_Source">Find</button> 
    </div>
</div>
<?php $escaper = new Zend\Escaper\Escaper('utf-8');
      if($this->countp >= 1) { ?>
      <table class="table table-striped table-condensed" style="font-size:8pt;">
     <thead>
         <tr>
			 <th></th>
             <th>Publisher</th>
             <th>Works</th>
         </tr>
     </thead>
     <tbody>
     <?php foreach($this->rows as $row) : ?>
    <tr>
    <div class="form-group">
	<td>
		<div class="radio">
        <label><input type="radio" id='sel_source' name="select_source" value=<?=$escaper->escapeHtml($row['name'])?>>
		</label>
        </div>
	</td>
    <td>
        <?php echo $escaper->escapeHtml($row['name']); ?>
    </td>
    <td> 
		<?php 
		//echo $escaper->escapeHtml($row['id']); 
		//fetch no of works based on id
        $table = new \App\Db\Table\WorkPublisher($adapter);
        $row = $table->findNoofWorks($row['id']);
        //var_dump($row);
		$no_of_works = $row[0]['cnt']; 
		echo $no_of_works;
		?>
    </td> 
    </div>    
    </tr>
	<?php endforeach; ?>
	<tr>
    <td valign="center">
    <br /><br />
    <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="button" class="btn btn-default" name="submitt" value="sel_Source" onClick="setText('sel_source');">Select</button> 
    </div>
    </div>
    </td>
    </tr>	
    </tbody>
    </table>
	<?php } ?> 	
    
</td>
</div> 


<div class="col-lg-6">
<td>
Destination Publisher<br /><br />
<div class="form-group">
    <label class="col-xs-2 control-label">Find: </label>
        <div class="col-xs-7">
            <input type="text" class="form-control" name="dest_publisher" id="destpublisher" size="50" maxlength="100" disabled/>
        </div>
</div>
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn btn-default" name="submitt" value="Find_Destination">Find</button> 
    </div>
</div>
</td>
</div>

</tr>

<tr>
<td valign="center">
<div class="form-group">
    <div class="col-lg-offset-4 col-lg-12">
        <button type="reset" class="btn btn-default" name="submitt" value="Clear">Clear</button>                 
    </div>
</div>
</td>
</tr>
</table>
</form>
</div>