<?php $this->headTitle('New Publisher'); ?>
<?php //$this->layout()->instructions = ""; ?>
 <?php                                       
                if ($request->getqueryParams('action') !== null) 
                {   
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                }
        
        
 ?>
<div class="col-md-4">
    <form class="form-horizontal" method="post" action="<?=$this->url('manage_publisher')?>">
    <input type="hidden" name="action" value="<?php echo $action; ?>">
        <div class="form-group">
            <label class="col-xs-2 control-label">Name: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="name_publisher" id="newpublisher" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button> 
                <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
            </div>
        </div>
    </form>   
</div>
