<?php $this->headTitle('Add Publisher Location'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-md-4">
<?php                                       
                $id;
                if ($request->getqueryParams('id') !== null) 
                {   
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                    $id = $params['id'];
                    //fetch name based on id
                    $table = new \App\Db\Table\Publisher($adapter);
                    $row = $table->findRecordById($id);
                    $name = $row['name'];
                    echo '<b>Publisher: </b>' . $name; 
                } 
?>
    <form class="form-horizontal" method="post" action="<?=$this->url('manage_publisherlocation')?><?='?id=' . $params['id']?>">
        <input type="hidden" name="action" value="<?php echo $action; ?>">
        <div class="form-group">
            <label class="col-xs-3 control-label">Location: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="add_publisherloc" id="addpublisherloc" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button> 
                <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
            </div>
        </div>
    </form>   
</div>
