INSERT INTO `translate_language` (`id`, `text_de`, `text_en`, `text_es`, `text_fr`, `text_it`, `text_nl`) 
VALUES (NULL, 'Karte', 'Card', 'Tarjeta', 'Carte', 'Scheda', 'Kaart'),
(NULL, 'Abschnitt','Section','Sección','Section','Sezione','Branche'),
(NULL, 'Kapitel','Chapter','Capítulo','Chapitre','Capitolo','Chapiter'),
(NULL, 'Teil','Part','Parte','Partie','Parte','Deel'),
(NULL, 'Überschrift','Heading','Título','Titre','Intestazione','Onderschrift'),
(NULL, 'Keyword','Keyword','Palabra clave','Keyword','Parola chiave','Keyword'),
(NULL, 'Durch','By','Por','Par','Da','Aan'),
(NULL, 'ISBN','ISBN','ISBN','ISBN','ISBN','ISBN'),
(NULL, 'Verleger','Publisher','Editor','Éditeur','Editore','Uitgeverij'),
(NULL, 'Veröffentlichen Sie Jahr','Publish Year','Publique El Año','Éditez L\'Année','Pubblichi L\'Anno','Uitgeverij Jaar'),
(NULL, 'Innen Gefunden','Found In','Encontrado Adentro','Trouvé Dedans','Trovato Dentro','Funderen'),
(NULL, 'Zeitschrift','Periodical','Periódico','Périodique','Periodico','Krant'),
(NULL, 'Ausgabe','Volume','Volumen','Volume','Volume','Geluidssterkte'),
(NULL, 'Zahl','Number','Número','Nombre','Numero','Aantal'),
(NULL, 'Beginnen Sie Seite','Start Page','Comience La Página','Commencez La Page','Inizi La Pagina',''),
(NULL, 'GesamtcSeiten','Total Pages','Páginas Totales','Pages Totales','Pagine Totali',''),
(NULL, 'Ausgabe','Edition','Edición','Édition','Edizione','Editie'),
(NULL, 'AusgabecJahr','Edition Year','Año De la Edición','Année D\'Édition','Anno Dell\'Edizione','Editie Jaar'),
(NULL, 'Reihe','Series','Serie','Série','Serie','Serie'),
(NULL, 'ReihencJahr','Series Year','Año De la Serie','Année De Série','Anno Di Serie','Serie Jaar'),
(NULL, 'Veranschaulicht worden','Illustrated','Ilustrado','Illustré','Illustrato',''),
(NULL, 'Autor','Author','Autor','Auteur','Autore','Auteur'),
(NULL, 'Herausgeber','Editor','Redactor','Rédacteur','Redattore','Editor'),
(NULL, 'Photograph','Photographer','Fotógrafo','Photographe','Photographer','Fotograaf'),
(NULL, 'Illustrator','Illustrator','Ilustrador','Illustrateur','Illustrator',''),
(NULL, 'Übersetzer','Translator','Traductor','Traducteur','Traduttore',''),
(NULL, 'Buch','Book','Libro','Livre','Libro','Book'),
(NULL, 'Versuch','Article','Artículo','Article','Articolo','Article'),
(NULL, 'Essay','Essay','Ensayo','Essai','Saggio','Essay'),
(NULL, 'Katalog','Catalog','Catálogo','Catalogue','Catalogo','Catalog'),
(NULL, 'Vortrag','Lecture','Conferencia','Conférence','Conferenza','Lecture'),
(NULL, 'Bildschirm','Video','Vídeo','Vidéo','Video','Video'),
(NULL, 'CD/DVD','CD/DVD','CD/DVD','CD/DVD','CD/DVD','CD/DVD'),
(NULL, 'Ansammlung','Collection','Colección','Collection','Accumulazione','Collection'),
(NULL, 'Titel','Title','Título','Titre','Titolo','Titel'),
(NULL, 'Untertitel','Subtitle','Subtítulo','Sous-titre','Sottotitolo','Ondertitel'),
(NULL, 'Parallel Title','Parallel Title','Parallel Title','Parallel Title','Parallel Title','Parallel Title'),
(NULL, 'Seriesnummer','Series Number','Número de Serie','Numéro de Série','Numero di Serie','Seriesnummer'),
(NULL, 'Attr_test_de','Attr_test_ST','Attr_test_es','Attr_test_fr','Attr_test_it','Attr_test_nl')



