<?php
$instructions['public'] = "PRODUCTION - Live since 21st, November 2005

                                 Running on NEW server September 2007";
$instructions['newwork'] = "Never use double quotes in the title, instead use single quotes when needed.";
$instructions['searchwork'] = "";
$instructions['managework'] = "Create a new card (use the lookup function to retrieve basic information based on the title) or select a title to review, change or publish an existing card.";
$instructions['reviewwork'] = "uji";
$instructions['classifywork'] = "";
$instructions['newworktype'] = "";	
$instructions['manageworktype'] = "";	
$instructions['attributesworktype'] = "";	
$instructions['newclassification'] = "";	
$instructions['manageclassification'] = "";	
$instructions['mergeclassification'] = "";	
$instructions['exportlistclassification'] = "";	
$instructions['newagent'] = "";	
$instructions['findagent'] = "";	
$instructions['manageagent'] = "";	
$instructions['mergeagent'] = "";
$instructions['newagenttype'] = "";	
$instructions['manageagenttype'] = "";	
$instructions['newpublisher'] = "";	
$instructions['findpublisher'] = "";	
$instructions['managepublisher'] = "";	
$instructions['mergepublisher'] = "";	
$instructions['new_language'] = "";	
$instructions['manage_language'] = "The english words cannot be changed.";	
$instructions['newusers'] = "";	
$instructions['manageusers'] = "";							 
$instructions['accessusers'] = "";	
$instructions['changepasswordpreferences'] = "Enter here your new password (second time for confirmation).";	
?>