<?php
$instructions['index.php'][''] = "PRODUCTION - Live since 21st, November 2005

Running on NEW server September 2007";
$instructions['tree.php']['showList'] = "";
$instructions['work.php']['showList'] = "Create a new card (use the lookup function to retrieve basic information based on the title) or select a title to review, change or publish an existing card.";
$instructions['work.php']['showForm'] = "Never use double quotes in the title, instead use single quotes when needed.";
$instructions['prefs.php']['handleForm'] = "Enter here your new password (second time for confirmation).";
$instructions['language.php']['handleForm'] = "The english words cannot be changed.";
$instructions['agent.php']['handleDelete'] = "test";
?>