<?php $this->headTitle('Merge Classification'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-md-4">
<form class="form-horizontal" method="post" action="<?=$this->url('manage_classification')?>">
<input type="hidden" name="action" value="<?=$action?>">
	<div class="form-group">  
		<label class="col-xs-4 control-label">Source: </label>
		<div class="col-xs-7">
			<select class="form-control" name="source_id">
				<option value=""></option>
				<option value="1">Biographie</option>
				<option value="3035">Oeuvres</option>
				<option value="10434">Doctrine</option>
				<option value="16938">Influence et Survie</option>
				<option value="19675"> </option>
			</select>
		</div>
	</div>
	
	<div class="form-group">  
		<label class="col-xs-4 control-label">Destination: </label>
		<div class="col-xs-7">
			<select class="form-control" name="destination_id">
				<option value=""></option>
				<option value="1">Biographie</option>
				<option value="3035">Oeuvres</option>
				<option value="10434">Doctrine</option>
				<option value="16938">Influence et Survie</option>
				<option value="19675"> </option>
			</select>
		</div>
	</div>
  <div class="form-group">
	<div class="col-sm-offset-4 col-sm-10">
		<button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button> 
        <button type="reset" class="btn btn-default" name="submitt" value="Cancel">Clear</button>
	</div>
  </div>
</form>
</div>