<?php $this->headTitle('New Classification'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-md-4">
<form class="form-horizontal" method="post" action="<?=$this->url('manage_classification')?>">
<input type="hidden" name="action" value="<?=$action?>">
  <div class="form-group">
	<label class="col-xs-4 control-label">Sort Order: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_classif_sortorder" id="newclassif_sortorder" />
	</div>
  </div>
	<div class="form-group">  
		<label class="col-xs-4 control-label">Parent: </label>
		<div class="col-xs-7">
			<select class="form-control" name="parent_id">
				<option value=""></option>
				<option value="1">Biographie</option>
				<option value="3035">Oeuvres</option>
				<option value="10434">Doctrine</option>
				<option value="16938">Influence et Survie</option>
				<option value="19675"> </option>
			</select>
		</div>
	</div>
  <div class="form-group">
	<label class="col-xs-4 control-label">English Title: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_classif_engtitle" id="newclassif_engtitle" />
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-4 control-label">French Title: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_classif_frenchtitle" id="newclassif_frenchtitle" />
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-4 control-label">German Title: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_classif_germantitle" id="newclassif_germantitle" />
	</div>
  </div>
  <div class="form-group">
  	<label class="col-xs-4 control-label">Dutch Title: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_classif_dutchtitle" id="newclassif_dutchtitle" />
	</div>
  </div>
  <div class="form-group">
  	<label class="col-xs-4 control-label">Spanish Title: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_classif_spanishtitle" id="newclassif_spanishtitle" />
	</div>
  </div>
  <div class="form-group">
  	<label class="col-xs-4 control-label">Italian Title: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_classif_italiantitle" id="newclassif_italiantitle" />
	</div>
  </div>
  <div class="form-group">
	<div class="col-sm-offset-4 col-sm-10">
		<button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button> 
        <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
	</div>
  </div>
</form>
</div>