<?php $this->headTitle('Change Password'); ?>
<?php //$this->layout()->instructions = "Enter here your new password (second time for confirmation)."; ?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
	$("#submit_Save").click( function() {
		var pwd = $("#change_pwd").val();
		var cfpwd = $("#confirm_pwd").val();
		if(!(pwd === cfpwd)) {			
			$('.loginError').show();
			$("#confirm_pwd").focus();
			return false;
		}
    });
});
</script>
<?php                                       
    if ($request->getqueryParams('action') !== null) 
    {   
        $params = $request->getqueryParams();
        $action = $params['action'];
    }        
 ?>
<div class="col-md-4">
<form class="form-horizontal" method="post">
<input type="hidden" name="action" value="<?=$action?>">
<div class="form-group"> 

	<label class="col-xs-4 control-label">Password: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="change_pwd" id="change_pwd" required="true"/>
	</div>	
	<br /> <br />
	<label class="col-xs-4 control-label">Confirm Password: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="confirm_pwd" id="confirm_pwd"/>
	</div>			
</div>
<div class="form-group">
	<div class="col-sm-offset-4 col-sm-10">
		<button type="submit" class="btn btn-default" name="submit_Save" id="submit_Save" value="Save">Save</button> 
        <!--<button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>-->
		<p class="loginError" style="display:none;color:red;margin-bottom:20px;">Change Password and confirm password must match</p>
	</div>
</div>
</form>
</div>