<?php $this->headTitle('Change Password'); ?>
<?php //$this->layout()->instructions = "Enter here your new password (second time for confirmation)."; ?>
<div class="col-md-4">
<form class="form-horizontal" method="post">
<div class="form-group"> 

	<label class="col-xs-4 control-label">Password: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_pwd" id="newpwd"/>
	</div>	
	<br /> <br />
	<label class="col-xs-4 control-label">Confirm Password: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="confirm_pwd" id="confirmpwd"/>
	</div>			
</div>
<div class="form-group">
	<div class="col-sm-offset-4 col-sm-10">
		<button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button> 
        <!--<button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>-->
	</div>
</div>
</form>
</div>
