<?php $this->headTitle('Attributes Work Type'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-md-9">
<a href="<?=$this->url('new_attribute')?><?='?action=new'?>">Add Attribute</a>
	<table class="table table-striped table-condensed" style="font-size:10pt;">
        <thead>
        <tr>
          <th>Attribute</th>
		  <th>Options</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
		<?php 
			$escaper = new Zend\Escaper\Escaper('utf-8'); 
			foreach($this->rows as $row) : 
				$output = (array)$row;
                $params = implode(', ', $output);        
		?>
        <tr>
        <td>
			<?php echo $escaper->escapeHtml($row['field']); ?>
		</td>
		<td>
			<a href="#">Manage Options</a>
			|
			<a href="#">Merge Duplicate Values</a>
		</td>
        <td>                   
            <a href="<?=$this->url('edit_attribute')?><?='?id=' . $row['id'] . '&action=edit'?>">Edit</a>        
			|
			<a href="<?=$this->url('delete_attribute')?><?='?id=' . $row['id'] . '&action=delete'?>">Delete</a>          			
        </td>
        </tr>
		<?php endforeach; ?>
        </tbody>
		</table>
		<?php if($this->countp > 1) { ?>
        <form method="get" action="page">
            <?=$this->paginationControl($this->rows,
                'Sliding',
                'app::controls',
                [
                    'route'  => 'attributes_worktype',
					'extraParams' => $searchParams,
                ]
            );?>
        </form>
        <?php } ?>
</div>
