<?php $this->headTitle('Attributes Work Type'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-md-9">
	<table class="table table-striped table-condensed" style="font-size:10pt;">
        <thead>
        <tr>
          <th>Attribute</th>
		  <th>Options</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        <tr>
        <td></td>
		<td>
			<a href="#">Manage Options</a>
			|
			<a href="#">Merge Duplicate Values</a>
		</td>
        <td>                   
            <a href="#">Edit</a>        
			|
			<a href="#">Move</a>          			
        </td>
        </tr>
        </tbody>
		</table>
</div>
