<?php $this->headTitle('Delete Option'); ?>
<?php //$this->layout()->instructions = ""; ?>
<?php
	$id;
	if ($request->getqueryParams('id') !== null) 
    {   
        $params = $request->getqueryParams();
        $action = $params['action'];
        $wkat_id = $params['wkat_id'];
		$id = $params['id'];
	}
?>
<div class="col-xs-4">
       <form method="post" action="<?=$this->url('manage_attribute_options')?><?= '?id=' . $wkat_id ?>">
        <p>Are you sure you want to delete this?</p>        
        <?php                                       
                
            if ($id !== null) 
            {   
                //fetch name based on id
                $table = new \App\Db\Table\WorkAttribute_Option($adapter);
                $row = $table->findRecordById($id);
                $title = $row['title'];
                echo "<p>$title</p>";
                //fetch no of works associated
                $table = new \App\Db\Table\Work_WorkAttribute($this->adapter);
                $paginator = $table->countRecordsByAttributeOption($wkat_id,$id);
                $cnt = $paginator->getTotalItemCount();
                echo "<p><b>There are $cnt works associated with it.</b></p>";
            } 
        ?>
        <ul>
        <input type="hidden" name="id" value="<?=$id?>">
        <input type="hidden" name="action" value="<?=$action?>">
        </ul>
        <input type="submit" name="submitt" value="Delete"> 
        <input type="submit" name="submitt" value="Cancel">
       </form>
   </div>

