<?php $this->headTitle('Delete Attribute'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-xs-4">
       <form method="post" action="<?=$this->url('attributes_worktype')?>">
        <p>Are you sure you want to delete this?</p>        
        <?php                                       
                $id;
                if ($request->getqueryParams('id') !== null) 
                {   
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                    $id = $params['id'];
                    //fetch name based on id
                    $table = new \App\Db\Table\WorkAttribute($this->adapter);
                    $row = $table->findRecordById($id);
                    $field = $row['field'];
                    echo "<p>$field</p>";
                    //fetch no of work types selected attribute is associated with
                    $table = new \App\Db\Table\WorkType_WorkAttribute($this->adapter);
                    $rows = $table->countWorkTypesByWorkAttributes($id);
                    echo "<p><b>This attribute is associated with " . $rows[0]['count_worktypes'] . " work types.</b></p>";
                } 
            ?>
        <ul>
        <input type="hidden" name="id" value="<?=$id?>">
        <input type="hidden" name="action" value="<?=$action?>">
        </ul>
        <input type="submit" name="submitt" value="Delete"> 
        <input type="submit" name="submitt" value="Cancel">
       </form>
   </div>