<?php $this->headTitle('Manage Options - Attributes'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-md-9">
<a href="#">Add Option</a>
<?php echo "page is $this->countp <br />"; ?>
	<table class="table table-striped table-condensed" style="font-size:10pt;">
        <thead>
        <tr>
		  <th>Option</th>
          <th>Type</th>
		  <th>Action</th>
        </tr>
        </thead>
        <tbody>
		<?php if($this->countp > 0) { ?>
		<?php 
			$escaper = new Zend\Escaper\Escaper('utf-8'); 
			foreach($this->rows as $row) : 
				$output = (array)$row;
                $params = implode(', ', $output);        
		?>
        <tr>
        <td>
			<?php echo $escaper->escapeHtml($row['title']); ?>
		</td>
		<td>
			<?php echo $escaper->escapeHtml($row['value']); ?>
		</td>
        <td>                   
            <a href="#">Edit</a>        
			|
			<a href="#">Delete</a>          			
        </td>
        </tr>
		<?php endforeach; ?>
		<?php } ?>
        </tbody>
		</table>
		<?php if($this->countp > 1) { ?>
        <form method="get" action="page">
            <?=$this->paginationControl($this->rows,
                'Sliding',
                'app::controls',
                [
                    'route'  => 'manage_attribute_options',
					'extraParams' => $searchParams,
                ]
            );?>
        </form>
        <?php } ?> 
</div>
