<?php $this->headTitle('Manage Work Type'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-md-9">
	<table class="table table-striped table-condensed" style="font-size:10pt;">
        <thead>
        <tr>
          <th>Work Type</th>
		  <th>Attributes</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
		<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
        <?php foreach($this->rows as $row) : ?>
        <tr>
        <td><?php echo $escaper->escapeHtml($row['type']); ?></td>
		<td><a href="#">Manage Attributes</a></td>
        <td>                   
            <a href="#">Edit</a>        
			|
			<a href="#">Move</a>          			
        </td>
        </tr>
		<?php endforeach; ?>
        </tbody>
		</table>
		<?php if($this->countp > 1) { ?>
        <form method="get" action="page">
            <?=$this->paginationControl($this->rows,
                'Sliding',
                'app::controls',
                [
                    'route'  => 'manage_worktype',
					'extraParams' => $searchParams,
                ]
            );?>
        </form>
        <?php } ?>
</div>