<?php $this->headTitle('Manage WorkType Attributes'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-md-9">
<?php                                       
        $id;
        if ($request->getqueryParams() !== null) 
        {   
            /*$queryString = implode('',$request->getqueryParams());
            $params = explode(',',$queryString); */
            $params = $request->getqueryParams();
            $id = $params['id'];           
        } 
        if ($id !== null) 
        {   
            //fetch name based on id
            $table = new \App\Db\Table\WorkType($adapter);
            $row = $table->findRecordById($id);
            $type = $row['type'];
            echo '<b>Attributes for: </b>'.$type.'<br/>'; 
?>
			Used attributes are checked <input type="checkbox" checked disabled>
<?php	}
?>
<form class="form-horizontal" method="post">
<table class="table table-striped table-condensed" style="font-size:10pt;">
     <thead>
         <tr>
             <th></th>
             <th>Order</th>
             <th>Attribute</th>
         </tr>
     </thead>
     <tbody>
     <?php 
		$table = new \App\Db\Table\WorkAttribute($this->adapter);
        $paginator = $table->displayAttributes();
		$escaper = new Zend\Escaper\Escaper('utf-8');
        foreach($paginator as $row) : 
	 ?>
     <form>
         <tr>
            <td>
                 <div class="checkbox">
                    <label><input type="checkbox" id='select' name="selectchk1[]" value=<?=$escaper->escapeHtml($row['id'])?>>                   
                    </label>
                 </div>
            </td>
			<td>
			</td>
            <td>
                <?php echo $escaper->escapeHtml($row['field']); ?>
            </td>            
         </tr>
         <?php endforeach; ?>
         </tbody>
</table>

<div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
            <input type="submit" class="btn btn-default" name="submitt" value="Add"/>
            <input type="submit" class="btn btn-default" name="submitt" value="Remove"/>
            </div>
</div>
</form>
</div>