<?php $this->headTitle('New Work Type'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-md-4">
<form class="form-horizontal" method="post" action="<?=$this->url('manage_worktype')?>">
<input type="hidden" name="action" value="<?=$action?>">
  <div class="form-group">
	<label class="col-xs-2 control-label">Type: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_worktype" id="newworktype" />
	</div>
  </div>
  <div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button> 
        <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
	</div>
  </div>
</form>
</div>