<?php $this->headTitle('New Attribute'); ?>
<?php //$this->layout()->instructions = ""; ?>
<?php                                       
        if ($request->getqueryParams('action') !== null) 
        {   
            $params = $request->getqueryParams();
            $action = $params['action'];
        }
        
        
 ?>
<div class="col-md-4">
<form class="form-horizontal" method="post" action="<?=$this->url('attributes_worktype')?>">
<input type="hidden" name="action" value="<?=$action?>">
<div class="form-group"> 

	<label class="col-xs-3 control-label">Attribute: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_attribute" id="newattribute"/>
	</div>	
	<br /> <br />
	<div class="radio">
		<label class="col-xs-3 control-label"><b>Field Type:</b> </label>
		<div class="col-xs-7">
        <label><input type="radio" name="field_type" value="Text">Short Text</label>
		<label><input type="radio" name="field_type" value="Textarea">Long Text</label>
		<label><input type="radio" name="field_type" value="Checkbox">True/False Box</label>
		<label><input type="radio" name="field_type" value="Select">Options Drop-Down</label>
		</div>
    </div>			
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button> 
        <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
	</div>
</div>
</form>
</div>