<?php $this->headTitle('Find Agent'); ?>
<div class="col-md-4">
    <form class="form-horizontal" method="get" action="<?=$this->url('manage_agent')?>">
        <div class="form-group">
            <label class="col-xs-4 control-label">First Name: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="find_agentfname" id="findagentfname" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-4 control-label">Last Name: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="find_agentlname" id="findagentlname" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-4 control-label">Alternate Name: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="find_agentaltname" id="findagentaltname" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-4 control-label">Organization Name: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="find_agentorgname" id="findagentorgname" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-10">
            <button type="submit" class="btn btn-default" name="submitt" value="Search">Search</button> 
            <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
            </div>
        </div>
    </form> 
</div>