<?php $this->headTitle('Manage Agent'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-md-12">     
<p>
<?php foreach ($this->carat as $value) { ?>
    <a href="<?=$this->url('manage_agent')?><?='?letter='. $value['letter']. '&action=alphasearch'?>">
    <?php echo ' '.$value['letter'].' '; ?></a><?php echo '|';  ?>
<?php } ?>
</p>
        <table class="table table-striped table-condensed" style="font-size:10pt;">
        <thead>
        <tr>
          <!-- <th>Id</th> -->
          <th>Name</th>
          <th>Alternate Name</th>
          <th>Organization Name</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
		<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
		<?php foreach($this->rows as $row) : ?>
		<tr>
		<!--<td><?php //echo $row['id']; ?></td>-->
		<td><?php echo $escaper->escapeHtml($row['lname'])." " . $escaper->escapeHtml($row['fname']); ?></td>
        <td><?php echo $escaper->escapeHtml($row['alternate_name']); ?></td>
        <td><?php echo $escaper->escapeHtml($row['organization_name']); ?></td>
        <td>            
            <?php $output = (array)$row;
                  $params = implode(', ', $output);        
            ?>        
            <a href="<?=$this->url('edit_agent')?><?='?id='. $row['id']. '&action=edit'?>">Edit</a>        
            |
            <a href="<?=$this->url('delete_agent')?><?='?id='. $row['id'].'&action=delete'?>">Delete</a>
        </td>
        </tr>
		<?php endforeach; ?>
        </tbody>
		</table>
         <?php if($this->countp > 1) { ?>
      <form method="get" action="page">
		<?=$this->paginationControl($this->rows,
                'Sliding',
                'app::controls',
                [
                    'route'  => 'manage_agent',
                    'extraParams' => $searchParams,
                ]
            );?>							   
		</form>
        <?php } ?>
</div>
