<?php $this->headTitle('New Agent'); ?>
<?php //$this->layout()->instructions = ""; ?>
<?php                                       
                if ($request->getqueryParams('action') !== null) 
                {   
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                }
        
        
 ?>
<div class="col-md-4">
<form class="form-horizontal" method="post" action="<?=$this->url('manage_agent')?>">
<input type="hidden" name="action" value="<?=$action?>">
  <div class="form-group">
	<label class="col-xs-4 control-label">First Name: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_agentfirstname" id="newagentfirstname" />
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-4 control-label">Last Name: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_agentlastname" id="newagentlastname" />
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-4 control-label">Alternate Name: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_agentaltname" id="newagentaltname" />
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-4 control-label">Organization Name: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_agentorgname" id="newagentorgname" />
	</div>
  </div>
  <div class="form-group">
	<div class="col-sm-offset-4 col-sm-10">
		<button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button> 
        <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
	</div>
  </div>
</form>
</div>