<?php $this->headTitle('New Work'); ?>
<?php //$this->layout()->instructions = "Never use double quotes in the title, instead use single quotes when needed."; ?>
<div class="col-md-7">
    <form id="personal-data" class="form-horizontal" method="POST" action="#">

<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class="active">
      <a href="#1" data-toggle="tab">General</a>
    </li>
    <li>
      <a href="#2" data-toggle="tab">Classification</a>
    </li>  
	<li>
      <a href="#3" data-toggle="tab">Publisher</a>
    </li>
	<li>
      <a href="#4" data-toggle="tab">Agents</a>
    </li>
	<li>
      <a href="#5" data-toggle="tab">Citation</a>
    </li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active in" id="General">      
		<div class="form-group">
			<label class="col-xs-2 control-label">Title: </label>
			<div class="col-xs-10">
				<input type="text" class="form-control" name="new_worktitle" id="newworktitle" />
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Sub Title: </label>
			<div class="col-xs-10">
				<input type="text" class="form-control" name="new_worksubtitle" id="newworksubtitle" />
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Parallel Title: </label>
			<div class="col-xs-10">
				<input type="text" class="form-control" name="new_workparalleltitle" id="newworkparalleltitle" />
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Description: </label>
			<div class="col-xs-10">
				<textarea class="form-control" placeholder="Message"></textarea>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Type: </label>
			<div class="col-xs-10">
				<select class="form-control" name="parent_id">
				<option value="">Type</option>					
				<?php
					//fetch worktypes
					$table = new \App\Db\Table\WorkType($this->adapter);
					$paginator = $table->fetchAllWorkTypes();
					foreach($paginator as $row) :
				?>
				<option value="<?=$row['id']?>"><?php echo $row['type']; ?></option>							
				<?php endforeach; ?>
				</select>
			</div>
		</div>
		<div class="form-group">
			<label class="col-xs-2 control-label">Parent Work: </label>
			<div class="col-xs-10">
				<button type="submit" class="btn btn-default" name="lookup_parent" value="parent_lookup">Lookup</button>
			</div>
		</div>		
		<div class="form-group">
			<label class="col-xs-2 control-label">Status: </label>
			<div class="col-xs-10">
				<div class="radio">
					<label class="radio"><input type="radio" id="selectworkstatus" name="select_workstatus" value="00">In Progress</label>
					<label class="radio"><input type="radio" id="selectworkstatus" name="select_workstatus" value="0">Pending Review</label>
					<label class="radio"><input type="radio" id="selectworkstatus" name="select_workstatus" value="2">Unseen Source Doc</label>
					<label class="radio"><input type="radio" id="selectworkstatus" name="select_workstatus" value="1">Complete</label>
				</div>
			</div>
		</div>		 
    </div>
    <div class="tab-pane" id="Classification">
      <!-- form controls to be continued here -->
      <p>Howdy, I'm in Section 2.</p>
    </div>            
  </div>
</div>
<div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<button type="submit" class="btn btn-default" name="submit_save" value="Save">Save</button> 
        <button type="submit" class="btn btn-default" name="submit_cancel" value="Cancel">Cancel</button>
	</div>
  </div>
</form>
</div>