<?php header('Content-Type: text/html; charset=UTF-8'); ?>
<?php $this->headTitle('Delete Language'); ?>
<?php //$this->layout()->instructions = "The english words cannot be changed."; ?>

   <div class="col-xs-4">
       <form method="post" action="<?=$this->url('manage_language')?>">
        <p>Are you sure you want to delete this?</p>
        <ul>
        <li><?php                                       
                $id;
                if ($request->getqueryParams('id') !== null) 
                {   
                    $params = $request->getqueryParams();
                    //echo $params['term']; 
                    $action = $params['action'];
                    $id = $params['id'];
                    //fetch name based on id
                    $table = new \App\Db\Table\TranslateLanguage($adapter);
                    $row = $table->findRecordById($id);
                    $name_en = $row['text_en'];
                    echo $name_en;
                } 
            ?>
        </li>
        <input type="hidden" name="id" value="<?=$id?>">
        <input type="hidden" name="action" value="<?=$action?>">
        </ul>
        <input type="submit" name="submitt" value="Delete"> 
        <input type="submit" name="submitt" value="Cancel">
       </form>
   </div>

