<?php $this->headTitle('Edit Language'); ?>
<?php //$this->layout()->instructions = ""; ?>

<?php                                       
        $id;
       /* if ($request->getqueryParams() !== null) 
        {   
            $queryString = implode('',$request->getqueryParams());
           // var_dump($queryString);
            $params = explode(',',$queryString); 
           // var_dump($params);
            //echo trim($params[1]);
        } */
       if ($request->getqueryParams('id') !== null) 
        {   
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                    $id = $params['id'];
                    //fetch name based on id
                    $table = new \App\Db\Table\TranslateLanguage($adapter);
                    $row = $table->findRecordById($id);
                    $name = $row['text_en'];
        } 
        
        
 ?>
<div class="col-md-4">
<form class="form-horizontal" method="post" action="<?=$this->url('manage_language')?>">
<input type="hidden" name="action" value="<?=trim($action)?>">
<input type="hidden" name="id" value="<?=trim($id)?>">
  <div class="form-group">   
	<label class="col-xs-2 control-label">de: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="de_newlang" id="denewlang" value="<?=trim($row['text_de'])?>" />
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-2 control-label">en: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="en_newlang" id="ennewlang" value="<?=trim($row['text_en'])?>" />
	</div>
  </div> 
  <div class="form-group">
	<label class="col-xs-2 control-label">es: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="es_newlang" id="esnewlang" value="<?=trim($row['text_es'])?>" />
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-2 control-label">fr: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="fr_newlang" id="frnewlang" value="<?=trim($row['text_fr'])?>" />
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-2 control-label">it: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="it_newlang" id="itnewlang" value="<?=trim($row['text_it'])?>" />
	</div>
  </div>
   <div class="form-group">
	<label class="col-xs-2 control-label">nl: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="nl_newlang" id="nlnewlang" value="<?=trim($row['text_nl'])?>" />
	</div>
  </div>
  <div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button> 
        <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
	</div>
  </div>
</form>
</div>

