<?php header('Content-Type: text/html; charset=UTF-8'); ?>
<?php $this->headTitle('Manage Language'); ?>
<?php //$this->layout()->instructions = "The english words cannot be changed."; ?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
</head>
<body>
    <div class="col-md-9">     
        <table class="table table-striped table-condensed" style="font-size:10pt;">
        <thead>
        <tr>
          <!-- <th>Id</th> -->
          <th>Text_De</th>
		  <th>Text_En</th>
		  <th>Text_Es</th>
		  <th>Text_Fr</th>
          <th>Text_It</th>
          <th>Text_Nl</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
		<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
		<?php foreach($this->rows as $row) : ?>
		<tr>
		<!--<td><?php //echo $row['id']; ?></td>-->
		<td><?php echo $escaper->escapeHtml($row['text_de']); ?></td>
		<td><?php echo $escaper->escapeHtml($row['text_en']); ?></td>
		<td><?php echo $escaper->escapeHtml($row['text_es']); ?></td>
		<td><?php echo $escaper->escapeHtml($row['text_fr']); ?></td>
        <td><?php echo $escaper->escapeHtml($row['text_it']); ?></td>
        <td><?php echo $escaper->escapeHtml($row['text_nl']); ?></td>
        <td>            
            <?php $output = (array)$row;
                  $params = implode(', ', $output);        
            ?>        
            <a href="<?=$this->url('edit_language')?><?php echo '?row='. urlencode($params).'&action=, edit'; /*echo '?id='. $row['id'].'&term='. $row['text_en'].'&action=edit';*/  ?>">Edit</a>        
            |
            <a href="<?=$this->url('delete_language')?><?php echo '?id='. $row['id'].'&term='. $row['text_en'].'&action=delete';  ?>">Delete</a>
        </td>
        </tr>
		<?php endforeach; ?>
        </tbody>
		</table>
      <form method="get" action="page">
		<?php echo $this->paginationControl($this->rows,
                                   'Sliding',
                              'app::controls', ['route'  => 'manage_language']); ?>
								   
		</form>	      
    </div>
</body>
</html>
