<?php $this->headTitle('New Language'); ?>
<?php //$this->layout()->instructions = ""; ?>
<?php 
    //if ($this->flashMessenger()->hasMessages()) {

        //echo '<div class="alert alert-info">';

    //    $messages = $this->flashMessenger()->getMessages();
   //     foreach($messages as $message) {
   //     echo $message;
   // }

   // echo '</div>';
//}
 ?>
 <?php                                       
                if ($request->getqueryParams('action') !== null) 
                {   
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                }
        
        
 ?>
<div class="col-md-4">
<form class="form-horizontal" method="post" action="<?=$this->url('manage_language')?>">
<input type="hidden" name="action" value="<?php echo $action; ?>">
  <div class="form-group">
	<label class="col-xs-2 control-label">de: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="de_newlang" id="denewlang" />
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-2 control-label">en: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="en_newlang" id="ennewlang" />
	</div>
  </div> 
  <div class="form-group">
	<label class="col-xs-2 control-label">es: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="es_newlang" id="esnewlang" />
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-2 control-label">fr: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="fr_newlang" id="frnewlang" />
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-2 control-label">it: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="it_newlang" id="itnewlang" />
	</div>
  </div>
   <div class="form-group">
	<label class="col-xs-2 control-label">nl: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="nl_newlang" id="nlnewlang" />
	</div>
  </div>
  <div class="form-group">
	<div class="col-sm-offset-2 col-sm-10">
		<button type="submit" class="btn btn-default" name="submitt" value="Save">Save</button> 
        <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
	</div>
  </div>
</form>
</div>

