<html>
<head>
  <title>Panta Rhei - Administration</title>
  <link rel="stylesheet" href="<?=$this->url('home')?>vendor/bootstrap-3.3.7-dist/css/bootstrap.min.css" >
  <link rel="stylesheet" href="<?=$this->url('home')?>css/main.css" media="screen" />
  <link rel="stylesheet" href="<?=$this->url('home')?>css/main_admin.css" media="screen" />
  <script type="text/javascript" src="<?=$this->url('home')?>js/menu.js"></script>
  <!-- <script src="<?=$this->url('home')?>js/dynamic-crumbs.js"></script> -->
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
</head>
<body>
<div class="banner">
  <h1>Bibliography</h1>
</div>
<br />
<div class="col-md-4">
<br /> <br />
<?php echo $this->content ?>
    <form class="form-horizontal" method="post" action="<?=$this->url('default')?><?='?action=new'.'&role=user'?>">
 <?php echo $this->url('new_work') ?>
        <div class="form-group">
            <label class="col-xs-3 control-label">User Name: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="user_name" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-xs-3 control-label">Password: </label>
            <div class="col-xs-7">
                <input type="text" class="form-control" name="user_pwd" />
            </div>
        </div>
        <div class="form-group">
            <label for="role">Select role (select one):</label>
                <select class="form-control" id="role" name="role">
                <option>Administrator</option>
                <option>User</option>
                </select>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-3 col-sm-10">
                <button type="submit" class="btn btn-default" name="submitt" value="Save">Login</button>
            </div>
        </div>
    </form>   
</div>
</body>
</html>
