<html>
<head>
  <title>Panta Rhei - Administration</title>
  <link rel="stylesheet" href="<?=$this->url('home')?>vendor/bootstrap-3.3.7-dist/css/bootstrap.min.css" >
  <link rel="stylesheet" href="<?=$this->url('home')?>css/main.css" media="screen" />
  <link rel="stylesheet" href="<?=$this->url('home')?>css/main_admin.css" media="screen" />
  <script type="text/javascript" src="<?=$this->url('home')?>js/menu.js"></script>
  <!-- <script src="<?=$this->url('home')?>js/dynamic-crumbs.js"></script> -->
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8">
</head>
<body>
<div class="banner">
  <h1>Administration</h1>
   <!--<div class="breadcrumb">
    <div class="item" style="float: left;"><a href="#home">Home / </a></div>
   <div style="float: left;">Home /</div>
    <div style="float: right;">
      [<a href="logout.php">Log Out</a>]
    </div>
  </div>-->
  

     <!--<div class="breadcrumb">
          <li><a href="#">Home /</a></li>
     </div>-->
  
</div>

<!-- Fixed navbar -->
    <div class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--<a class="navbar-brand" href="#">Administration</a>-->
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right pull-left">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Work<b class="caret"></b></a>			  
              <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_work') ?>">New</a></li>
                <li><a href="<?php echo $this->url('search_work') ?>">Search</a></li>
				<li><a href="<?php echo $this->url('manage_work') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('review_work') ?>">Review</a></li>
				<li><a href="<?php echo $this->url('classify_work') ?>">Classify</a></li>
				</ul>
				</li>
				<li class="divider-vertical"></li>
				 <li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Work Type<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_worktype') ?>">New</a></li>
                <li><a href="<?php echo $this->url('manage_worktype') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('attributes_worktype') ?>">Attributes</a></li>
              </ul>
            </li>       

              <li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Classification<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_classification') ?>">New</a></li>
                <li><a href="<?php echo $this->url('manage_classification') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('merge_classification') ?>">Merge</a></li>
				<li><a href="<?php echo $this->url('exportlist_classification') ?>">Export List</a></li>
              </ul>
            </li>  			
            
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Agent<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_agent') ?>">New</a></li>
                <li><a href="<?php echo $this->url('find_agent') ?>">Find</a></li>
				<li><a href="<?php echo $this->url('manage_agent') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('merge_agent') ?>">Merge</a></li>
              </ul>
            </li>  
			
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Agent Type<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_agenttype') ?>">New</a></li>
				<li><a href="<?php echo $this->url('manage_agenttype') ?>">Manage</a></li>
              </ul>
            </li> 
			
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Publisher<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_publisher') ?>">New</a></li>
                <li><a href="<?php echo $this->url('find_publisher') ?>">Find</a></li>
				<li><a href="<?php echo $this->url('manage_publisher') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('merge_publisher') ?>">Merge</a></li>
              </ul>
            </li> 
			
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Language<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_language') ?>">New</a></li>
				<li><a href="<?php echo $this->url('manage_language') ?>">Manage</a></li>
              </ul>
            </li> 
			
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Users<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('new_users') ?>">New</a></li>
				<li><a href="<?php echo $this->url('manage_users') ?>">Manage</a></li>
				<li><a href="<?php echo $this->url('access_users') ?>">Access</a></li>
              </ul>
            </li> 
			
			<li class="dropdown">           
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">Preferences<b class="caret"></b></a>
				 <ul class="dropdown-menu">
                <li><a href="<?php echo $this->url('changepassword_preferences') ?>">Change Password</a></li>
              </ul>
            </li> 
			
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="<?=$this->url('home')?>vendor/bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>
 <div class="app-content">
 <?php
			
			// Page Instructions Content
            //include_once('instructions.inc');
			
            $page = basename($this->url());
	
            //echo $instructions[basename($this->url())];
	      
           if (isset($_POST['instructions'])) {
			  // print_r($_POST['instructions']);
            $instructions[basename($this->url())] = $_POST['instructions'];
           }

	      // print_r($instructions);
	        $this->layout()->instructions = isset($instructions[$page])
                    ? $instructions[$page] : ''; 
?>
        <main class="container">
            <?php echo $this->content ?>
				<div style="float: right; width: 240px;">
				<div class="tipbox">
				<div>Instructions</div>
				<form method="post" name="ins_box">
				<input type="hidden" name="action" value="ins">
				<textarea name="instructions" rows="5" cols="22"><?php echo $this->layout()->instructions; ?></textarea><br>
				<input type="submit" name="submit" value="Save">
				</form>
				</div>
			   </div>
			
        </main>
</div>

</body>
</html>
