<?php $this->headTitle('Delete AgentType'); ?>
<?php //$this->layout()->instructions = "The english words cannot be changed."; ?>

   <div class="col-xs-4">
       <form method="post" action="<?=$this->url('manage_agenttype')?>">
        <p>Are you sure you want to delete this?</p>        
        <?php                                       
                $id;
                if ($request->getqueryParams('id') !== null) 
                {   
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                    $id = $params['id'];
                    //fetch name based on id
                    $table = new \App\Db\Table\AgentType($adapter);
                    $row = $table->findRecordById($id);
                    $type = $row['type'];
                    echo "<p>$type</p>";
                    //fetch no of works associated
                    $table = new \App\Db\Table\WorkAgent($this->adapter);
                    $paginator = $table->countRecords($id);
                    $cnt = $paginator->getTotalItemCount();
                    echo "<p><b>There are $cnt works associated with it.</b></p>";
                } 
            ?>
        <ul>
        <input type="hidden" name="id" value="<?=$id?>">
        <input type="hidden" name="action" value="<?=$action?>">
        </ul>
        <input type="submit" name="submitt" value="Delete"> 
        <input type="submit" name="submitt" value="Cancel">
       </form>
   </div>

