<?php $this->headTitle('Access Users'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-md-9">
<form class="form-horizontal" method="post">
<table class="table table-striped table-condensed" style="font-size:10pt;">
     <thead>
         <tr>
             <th>Title</th>
             <th>Access</th>
         </tr>
     </thead>
     <tbody>
		<form>
        <tr>
            <td>
				Administrator
            </td>
            <td> 
				<table style="font-size:10pt;">
				<tr align="center">
				<td>
				Work <br>
				<div class="checkbox">				
				<input type="checkbox" name="access[Work][Administrator]" value="1" checked disabled>
				</div>
				</td>
				<td>
				Work Type <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Work Type][Administrator]" value="1" checked disabled>
				</div>
				</td>
				<td>
				Classification <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Classification][Administrator]" value="1" checked disabled>
				</div>
				</td>
				<td>
				Agent <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Agent][Administrator]" value="1" checked disabled>
				</div>
				</td>
				<td>
				Agent Type <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Agent Type][Administrator]" value="1" checked disabled>
				</div>
				</td>
				<td>
				Publisher <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Publisher][Administrator]" value="1" checked disabled>
				</div>
				</td>
				<td>
				Language <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Language][Administrator]" value="1" checked disabled>
				</div>
				</td>
				<td>
				Users <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Users][Administrator]" value="1" checked disabled>
				</div>
				</td>
				<td>
				Preferences <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Preferences][Administrator]" value="1" checked disabled>
				</div>
				</td>
				</tr>
				</table>
            </td>              
        </tr>
		<tr>
            <td>
				Super User
            </td>
            <td> 
				<table style="font-size:10pt;">
				<tr align="center">
				<td>Work <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Work][Super User]" value="1" checked>
				</div>
				</td>
				<td>Work Type <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Work Type][Super User]" value="1">
				</div>
				</td>
				<td>Classification <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Classification][Super User]" value="1" checked>
				</div>
				</td>
				<td>Agent <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Agent][Super User]" value="1" checked>
				</div>
				</td>
				<td>Agent Type <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Agent Type][Super User]" value="1">
				</div>
				</td>
				<td>Publisher <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Publisher][Super User]" value="1" checked>
				</div>
				</td>
				<td>Language <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Language][Super User]" value="1">
				</div>
				</td>
				<td>Users <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Users][Super User]" value="1">
				</div>
				</td>
				<td>Preferences <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Preferences][Super User]" value="1" checked>
				</div>
				</td>
				</tr>
				</table>
            </td>              
        </tr>
		<tr>
            <td>
				User
            </td>
            <td>   
				<table style="font-size:10pt;">
				<tr align="center">
				<td>Work <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Work][User]" value="1" checked>
				</div>
				</td>
				<td>Work Type <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Work Type][User]" value="1">
				</div>
				</td>
				<td>Classification <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Classification][User]" value="1">
				</div>
				</td>
				<td>Agent <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Agent][User]" value="1" checked>
				</div>
				</td>
				<td>Agent Type <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Agent Type][User]" value="1">
				</div>
				</td>
				<td>Publisher <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Publisher][User]" value="1" checked>
				</div>
				</td>
				<td>Language <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Language][User]" value="1">
				</td>
				<td>Users <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Users][User]" value="1">
				</td>
				<td>Preferences <br>
				<div class="checkbox">
				<input type="checkbox" name="access[Preferences][User]" value="1" checked>
				</td>
				</table>
            </td>              
        </tr>
         </tbody>
</table>

<div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
            <input type="submit" class="btn btn-default" name="submitt" value="Save"/>
            <input type="submit" class="btn btn-default" name="submitt" value="Cancel"/>
            </div>
</div>
</form>
</div>
