<?php $this->headTitle('Access Users'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-md-9">
<form class="form-horizontal" method="post">
<table class="table table-striped table-condensed" style="font-size:10pt;">
     <thead>
         <tr>
             <th>Title</th>
             <th>Access</th>
         </tr>
     </thead>
     <tbody>
		<form>
        <tr>
            <td>
				Administrator
            </td>
            <td>                
            </td>              
        </tr>
		<tr>
            <td>
				Super User
            </td>
            <td>                
            </td>              
        </tr>
		<tr>
            <td>
				User
            </td>
            <td>                
            </td>              
        </tr>
         </tbody>
</table>

<div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
            <input type="submit" class="btn btn-default" name="submitt" value="Save"/>
            <input type="submit" class="btn btn-default" name="submitt" value="Cancel"/>
            </div>
</div>
</form>
</div>
