<?php $this->headTitle('Delete User'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-xs-4">
    <form method="post" action="<?=$this->url('manage_users')?>">
        <p>Are you sure you want to delete?</p>        
        <?php                                       
                $id;
                if ($request->getqueryParams('id') !== null) 
                {   
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                    $id = $params['id'];
					//echo $id;
                    //fetch name based on id
                    $table = new \App\Db\Table\User($adapter);
                    $row = $table->findRecordById($id);
                    $name = $row['name'];
					$username = $row['username'];
                    echo "<p>user " . $name . " with username as " . $username . "</p>";
				} 
        ?>
        <ul>
        <input type="hidden" name="id" value="<?=$id?>">
        <input type="hidden" name="action" value="<?=$action?>">
        </ul>
        <input type="submit" name="submitt" value="Delete"> 
        <input type="submit" name="submit_Cancel" value="Cancel">
    </form>
</div>