<?php $this->headTitle('Edit User'); ?>
<?php //$this->layout()->instructions = ""; ?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
	$("#submit_Save").click( function() {
		var pwd = $("#new_user_pwd").val();
		var cfpwd = $("#confirm_pwd").val();
		if(!(pwd === cfpwd)) {			
			$('.loginError').show();
			$("#confirm_pwd").focus();
			return false;
		}
    });
});
</script>
<?php                                       
        $id;
       if ($request->getqueryParams('id') !== null) 
        {   
                    $params = $request->getqueryParams();
                    $action = $params['action'];
                    $id = $params['id'];
                    //fetch name based on id
                    $table = new \App\Db\Table\User($this->adapter);
                    $row = $table->findRecordById($id);
                    $name = $row['name'];
					//$level = $row['level'];
					$username = $row['username'];
					$pwd = $row['password'];
					if(isset($row['level'])) {
						if ($row['level'] == 1) 
							$level = "Administrator";
						else
							$level = "Super User";
					}
					else
						$level = "User";
        }                
 ?>
<div class="col-md-4">
<form class="form-horizontal" method="post" action="<?=$this->url('manage_users')?>">
<input type="hidden" name="action" value="<?=trim($action)?>">
<input type="hidden" name="id" value="<?=trim($id)?>">
  <div class="form-group">
	<label class="col-xs-4 control-label">Name: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="newuser_name" id="username" value="<?=$name?>"/>
	</div>
  </div>
	<div class="form-group">  
		<label class="col-xs-4 control-label">Access Level: </label>
		<div class="col-xs-7">
			<select class="form-control" name="access_level">
				<option value="1" 
				<?php 
					if($level=="Administrator") 
						echo 'selected="selected"'; 
				?>>
				Administrator
				</option>
				<option value="0" 
				<?php 
					if($level=="Super User") 
						echo 'selected="selected"';
				?>>
				Super User
				</option>
				<option value="NULL" 
				<?php 
					if($level=="User") 
						echo 'selected="selected"'; 
				?>>
				User
				</option>
			</select>
		</div>
	</div>
  <div class="form-group">
	<label class="col-xs-4 control-label">Username: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_username" id="new_username" required="true" value="<?=$username?>"/>
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-4 control-label">Password: </label>
	<div class="col-xs-7">
		<input type="password" class="form-control" name="new_user_pwd" id="new_user_pwd" required="true" value="<?=$pwd?>"/>
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-4 control-label">Confirm Password: </label>
	<div class="col-xs-7">
		<input type="password" class="form-control" name="confirm_pwd" id="confirm_pwd" required="true" value="<?=$pwd?>"/>
	</div>
  </div>
  <div class="form-group">
	<div class="col-sm-offset-4 col-sm-10">
		<button type="submit" class="btn btn-default" name="submit_Save" id="submit_Save" value="Save">Save</button> 
        <button type="submit" class="btn btn-default"  name="submit_Cancel" value="Cancel">Cancel</button>
		<p class="loginError" style="display:none;color:red;margin-bottom:20px;">Password and confirm password must match</p>
	</div>
  </div>
</form>
</div>

