<?php $this->headTitle('Manage Users'); ?>
<?php //$this->layout()->instructions = ""; ?>
<div class="col-md-9">
	<table class="table table-striped table-condensed" style="font-size:10pt;">
        <thead>
        <tr>
          <th>Name</th>
          <th>Actions</th>
		  <th>Access Level</th>
        </tr>
        </thead>
        <tbody>
		<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
        <?php foreach($this->rows as $row) : 
				$output = (array)$row;
                $params = implode(', ', $output);        
		?>
        <tr>
        <td>
			<?php echo $escaper->escapeHtml($row['name']); ?>
		</td>
        <td>			             
            <a href="#">Edit</a>        
            |
            <a href="#">Delete</a>   			
        </td>
		<td>
			<?php 
				if(isset($row['level'])) {
					if ($row['level'] == 1) 
						echo "Administrator";
					else
						echo "Super User";
				}
				else
					echo "User";
			?>
		</td>
        </tr>
		<?php endforeach; ?>
        </tbody>
		</table>
		<?php if($this->countp > 1) { ?>
        <form method="get" action="page">
            <?=$this->paginationControl($this->rows,
                'Sliding',
                'app::controls',
                [
                    'route'  => 'manage_users',
					'extraParams' => $searchParams,
                ]
            );?>
        </form>
        <?php } ?>
</div>
