<?php $this->headTitle('New Users'); ?>
<?php //$this->layout()->instructions = ""; ?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript" src="js/registration.js"></script>
<script>
$(document).ready(function() {
$('input[type="button"][value="Save"]').click(function() {
        rules: {
            new_username: {
                required: true
            },
            new_user_pwd: {
                required: true
            },
			confirm_pwd: { 
				equalTo: "#new_user_pwd",
			},
        messages: {
            new_username: {
                required: "please specify username"
            },
            new_user_pwd: {
                required: "please specify password"
            },
			confirm_pwd: {
				equalTo: "Password and confirm password must match"
			}
        },
		
    });
});
});
</script>
<div class="col-md-4">
<form class="form-horizontal" id="newuserform" name="newuserform" method="post" action="">
  <div class="form-group">
	<label class="col-xs-4 control-label">Name: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="newuser_name" id="username" />
	</div>
  </div>
	<div class="form-group">  
		<label class="col-xs-4 control-label">Access Level: </label>
		<div class="col-xs-7">
			<select class="form-control" name="access_level">
				<option value="1">Administrator</option>
				<option value="0">Super User</option>
				<option value="NULL">User</option>
			</select>
		</div>
	</div>
  <div class="form-group">
	<label class="col-xs-4 control-label">Username: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_username" id="new_username"/>
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-4 control-label">Password: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_user_pwd" id="new_user_pwd" required="true"/>
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-4 control-label">Confirm Password: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="confirm_pwd" id="confirm_pwd" required="true"/>
	</div>
  </div>
  <div class="form-group">
	<div class="col-sm-offset-4 col-sm-10">
		<button type="submit" class="btn btn-default" name="submitt" id="submit" value="Save">Save</button> 
        <button type="submit" class="btn btn-default" name="submitt" value="Cancel">Cancel</button>
	</div>
  </div>
</form>
</div>