<?php $this->headTitle('New Users'); ?>
<?php //$this->layout()->instructions = ""; ?>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script>
$(document).ready(function() {
	$("#submit_Save").click( function() {
		var pwd = $("#new_user_pwd").val();
		var cfpwd = $("#confirm_pwd").val();
		if(!(pwd === cfpwd)) {			
			$('.loginError').show();
			$("#confirm_pwd").focus();
			return false;
		}
    });
});
</script>
<?php                                       
    if ($request->getqueryParams('action') !== null) 
    {   
        $params = $request->getqueryParams();
        $action = $params['action'];
    }        
 ?>
<div class="col-md-4">
<form class="form-horizontal" id="newuserform" name="newuserform" method="post" action="<?=$this->url('manage_users')?>">
<input type="hidden" name="action" value="<?=$action?>">
  <div class="form-group">
	<label class="col-xs-4 control-label">Name: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="newuser_name" id="username" />
	</div>
  </div>
	<div class="form-group">  
		<label class="col-xs-4 control-label">Access Level: </label>
		<div class="col-xs-7">
			<select class="form-control" name="access_level">
				<option value="1">Administrator</option>
				<option value="0">Super User</option>
				<option value="NULL">User</option>
			</select>
		</div>
	</div>
  <div class="form-group">
	<label class="col-xs-4 control-label">Username: </label>
	<div class="col-xs-7">
		<input type="text" class="form-control" name="new_username" id="new_username" required="true"/>
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-4 control-label">Password: </label>
	<div class="col-xs-7">
		<input type="password" class="form-control" name="new_user_pwd" id="new_user_pwd" required="true"/>
	</div>
  </div>
  <div class="form-group">
	<label class="col-xs-4 control-label">Confirm Password: </label>
	<div class="col-xs-7">
		<input type="password" class="form-control" name="confirm_pwd" id="confirm_pwd" required="true"/>
	</div>
  </div>
  <div class="form-group">
	<div class="col-sm-offset-4 col-sm-10">
		<button type="submit" class="btn btn-default" name="submit_Save" id="submit_Save" value="Save">Save</button> 
        <button type="submit" class="btn btn-default"  name="submit_Cancel" value="Cancel">Cancel</button>
		<p class="loginError" style="display:none;color:red;margin-bottom:20px;">Password and confirm password must match</p>
	</div>
  </div>
</form>
</div>